/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.0/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
    java
    war
}

group = "org.example"
version = "1.0.0-SNAPSHOT"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Spring Boot Starter for building web applications, including RESTful applications using Spring MVC. Uses Tomcat as the default embedded container
    implementation(libs.spring.boot.starter.web)
    implementation(libs.spring.boot.starter.actuator)
    implementation(libs.spring.boot.starter.validation)

    implementation(libs.spring.boot.starter.data.jpa)

    providedRuntime("org.springframework.boot:spring-boot-starter-tomcat")

    runtimeOnly(libs.h2)

    // Use the Spring Boot Starter Test for testing Spring Boot applications with libraries including JUnit Jupiter, Hamcrest and Mockito.
    testImplementation(libs.spring.boot.starter.test)
}

tasks.test {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}


// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

springBoot {
    mainClass.set("org.example.App")
}

tasks.jar {
    enabled = false
}