/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.springframework.boot.test.context.SpringBootTest;

import java.beans.Transient;

@SpringBootTest
class AppTest {

    @Test
    void contextLoads() {
    }
}
